import Head from "next/head";
import About from "../components/home/About";
import Hero from "../components/home/Hero";
import Sponsors from "../components/home/Sponsors";
import useScroll from "../lib/use-scroll";

export default function Home() {
  const [aboutRef, scrollToAboutRef] = useScroll();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero scrollToAboutRef={scrollToAboutRef} />
      <Sponsors />
      <About aboutRef={aboutRef} />
    </div>
  );
}
