import Head from "next/head";
import Hero from "../components/home/Hero";
import Sponsors from "../components/home/Sponsors";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Sponsors />
    </div>
  );
}
